### ISSUE TITLE
Stumped HW 4

### ISSUE THREAD

**Issue by rtorzilli** [rtorzilli/Methods-for-Neutral-Particle-Transport#9]
Good Evening Captain Bevins,

 I was hoping to be able to fix whatever was going on in my mcnp decks but I can't figure it out.

city.i gets a geometry error: no cell found
        (VisEd glitches out so my geometry is in a Quantum State for all I know)
Torzilli_prb2.i gets a Fatal error: 1 tally volumes or areas were not input nor calculated

Any help would be appreciated,
Robert Torzilli

![city](https://user-images.githubusercontent.com/32455726/33299671-a9be0372-d3ba-11e7-924d-74b3f4a2d9d7.PNG)
![torzilli_prb2](https://user-images.githubusercontent.com/32455726/33299672-a9cc450e-d3ba-11e7-84d7-188658c03d62.PNG)

**Comment by JediJun** [comment]
Use SDn after Tally n card, may solve this problem.
Please check manual "SD Segment Divisor (tally types 1, 2, 4, 6, 7) ".
